### ISSUE TITLE
Congratulation you are authenticated ! However there is nothing to do here

### ISSUE THREAD

**Issue by chanyshev** [Crivaledaz/Mattermost-LDAP#111]
Hello
I'm trying to set up integration with AD

**Describe the bug**
Congratulation you are authenticated !
However there is nothing to do here ...

**To Reproduce**
1. Go to 'http://mattermost.website.com/oauth/access_token'
2. I fill in the login and password
3. See error "Congratulation you are authenticated !
However there is nothing to do here ..."

Provide commands, Mattermost and PHP logs or configuration file if possible.
```
  php:
    image: php-ldap-pgsql
    container_name: ldap-oauth
    volumes:
      - ./oauth:/var/www/html/oauth
    ports:
      - "9000:9000"
    environment:
      ldap_host: ldap://$ip:389/
      ldap_port: 389
      ldap_version: 3
      ldap_search_attribute: "sAMAccountName"
      ldap_base_dn: "ou=users,dc=domain,dc=com"
      ldap_filter: "(&(objectClass=user))"
      ldap_bind_dn: "CN=mattermost,OU=Service users,OU=users,DC=domain,DC=com"
      ldap_bind_pass: "password"
      db_host: "database"
      db_port: "5432"
      db_type: "pgsql"
      db_name: "oauth_db"
      db_user: "oauth"
      db_pass: "password"
    depends_on:
      - database
```

**Screenshots**
![image](https://github.com/Crivaledaz/Mattermost-LDAP/assets/44210753/1ca9a833-a23b-4e89-9959-60299592a621)

**Project (please complete the following information):**

-   Project Version: (e.g. version v1.1)

**Desktop (please complete the following information):**
-   OS: Ubuntu 22
-   Browser: chrome

**Additional context**
```
mattermost-mattermost-1  | {"timestamp":"2023-11-17 07:15:00.004 Z","level":"error","msg":"Failed to get system bot","caller":"app/post.go:2165","error":"GetSystemBot: List of admins is empty."}
```
