### ISSUE TITLE
Redirect_uri_mismatch

### ISSUE THREAD

**Issue by Arcticold** [Crivaledaz/Mattermost-LDAP#30]
Hi!
I don't understand what I need to set as redirect_uri. Whatever I've tried so far results in "redirect_uri_mismatch". When I go to the login page of Mattermost and hover over GitLab button, the URL it displays is "192.168.1.59:8065/oauth/gitlab/login".
The config.json file is configured as instructed, but when I take a look at system console, the following can be seen: 
![image](https://user-images.githubusercontent.com/5424359/57606706-15902300-7572-11e9-82a3-288476c678d0.png)

**Comment by Crivaledaz** [comment]
Hi,

Assuming configuration in `config.json` is valid. When you click on the Gitlab button on the Mattermost login page, you are redirected to the authorize page from the oauth server :
```
http://<oauth_server>/oauth/authorize.php?response_type=code&client_id=<token_client>&redirect_uri=http://<mattermost_server>/signup/gitlab/complete&state=<state_token>
```

The error "redirect_uri_mismatch" comes when the `redirect_uri` values in the table `oauth_clients`, from the oauth database, is not equal to the url parameter `redirect_uri`. 

For example, if `redirect_uri` value in the database is `http://<mattermost_hostname>/signup/gitlab/complete` and the url `redirect_uri` parameter is `http://<mattermost_ip>/signup/gitlab/complete`, you will get the error "redirect_uri_mismatch" because `<mattermost_hostname> != <mattermost_ip>` even if this is the same server.

Concerning the Gitlab configuration in Mattermost, configuration in `config.json` is overridden configuration in the System Console. Thus, be sure your Mattermost `config.json` is well configured with the following parameters : 
```
  gitlab:
    Enable: "true"
    Secret: "<client_secret>"
    Id: "<client_id>"
    Scope: ""
    AuthEndpoint: "https://<oauth_server>/oauth/authorize.php"
    TokenEndpoint: "http://<oauth_server>/oauth/token.php"
    UserApiEndpoint: "http://<oauth_server>/oauth/resource.php"
```

Please check your configuration, and the `redirect_uri` value in oauth database (table `oauth_clients`), and try again.

I hope these will solve your problem, please give me your feedback,

Regards
